<li class="feeds-item beer beer_<?php echo $beer['user_id']; ?>" data-id="<?php echo $beer['user_id']; ?>">
   <div class="data-container">        
		<a href="<?php echo $wo['config']['site_url'];?>/<?php echo $beer['username']; ?>">
			<img class="data-avatar" src="<?php echo $beer['user_picture']; ?>" alt="<?php echo $beer['username']; ?>" width="50">
		</a>
        <div class="data-content">
		
			<div class="pull-right flip delete_beer">
				<button type="button" class="close"><span>×</span></button>
			</div>           
			
			<div class="beer_sending pull-right flip x-hidden">
				<?php echo $wo['lang']['plugin_beer_gave_a_beer']; ?>
				<a href="<?php echo $wo['config']['site_url'];?>/<?php echo $beer['username']; ?>"><?php echo $beer['username']; ?></a>!
			</div>
			
            <div class="pull-right flip">
				<button type="button" class="btn btn-primary btn_beer" data-id="<?php echo $beer['user_id']; ?>">
					<img src="<?php echo $wo['config']['site_url'];?>/assets/plugins/beer/img/beer2.png">
					<span class="ml5">
						<?php 
						if($suggest == 0){
							echo $wo['lang']['plugin_beer_return_beer'];
						} else {
							echo $wo['lang']['plugin_beer_give_a_beer'];
						} ?>
					</span>
				</button>
			</div>
			
            <div>
                <span class="name js_user-popover"  data-uid="<?php echo $beer['user_id']; ?>" data-type="user">
                    <a href="<?php echo $wo['config']['site_url'];?>/<?php echo $beer['username']; ?>"><?php echo $beer['user_fullname']; ?></a>
                </span>
				<?php if($suggest == 0){ ?>
					<div class="post-time"><a class="js_moment" data-time="<?php echo $beer['time']; ?>"><?php echo $beer['time']; ?></a></div>
				<?php } ?>
            </div>
			
        </div>
		
    </div>
</li>