<tr class="setting-postlist" id="<?php echo $wo['lang_key'];?>">
   <td><?php echo $wo['lang_key'];?></td>
   <td><?php echo $wo['langs'];?></td>
   <td>
      <a class="delete-post pointer" href="<?php echo $wo['config']['site_url']?>/index.php?link1=admin-plugins&view=edit_key&id=<?php echo $wo['lang_key']; ?>"><i class="fa fa-pencil-square progress-icon" data-icon="trash-o"></i> Edit</a>
   </td>
</tr>