<?php 
global $sqlConnect, $sub_view,$uptransaction_states;

//id user
$sub_view = ( isset($_POST['sub_view']) ? $_POST['sub_view'] : ( isset($_GET['sub_view']) ? $_GET['sub_view'] : 0 ) );
				
if($sub_view != 0){
	$query = " SELECT * FROM uptransactions  WHERE user_id = '{$sub_view}' ";
	// GET TOTAL ITEMS
	$sql_count = $sqlConnect->query($query);
	$total_items = $sql_count->num_rows;
	$sql = $query." ORDER BY date DESC";
	$rows = $sqlConnect->query( $sql );
	
	$items = array();
	while($row = $rows->fetch_assoc()){ 
		$row['_date'] = date('Y-m-d H:i:s', $row['date']);
		$row['state'] = $uptransaction_states[$row['state']];
		$items[] = $row;
	}	
	/* vault */
	$points_all = userpoints_get_all($sub_view);
	if($points_all) {
	   $user_points = $points_all['count'];
	   $user_points_totalearned = $points_all['totalearned'];
	} else {
	   $user_points = 0;
	   $user_points_totalearned = 0;
	}	
	$user_rank = userpoints_get_rank($sub_view);	
} else {	
	$sql_head = "SELECT U.user_id, U.email, U.username, U.first_name, U.last_name, U.avatar,
	IF(ISNULL(P.count), 0, P.count) AS count,
	IF(ISNULL(P.totalearned), 0, P.totalearned) AS totalearned";
	
	$sql_body = "FROM Wo_Users U
	LEFT JOIN userpoints P ON U.user_id = P.user_id";
	
	$sql_count = $sqlConnect->query('SELECT COUNT(*)' . ' ' . $sql_body);	
	$sql_users = $sql_head  . ' ' . $sql_body;
		
	// GET TOTAL USERS
	$total_users = $sql_count->num_rows;
	
	$sql_users .= " ORDER BY user_id ASC";
	$resource = $sqlConnect->query($sql_users);
	$rows = array();
	while($row = $resource->fetch_assoc()){
		if($row['avatar']!= ''){ $row['user_picture'] =  $row['avatar']; } else { $row['user_picture'] = 'upload/photos/d-avatar.jpg'; }
		if($row['first_name']!= ''){ $row['user_fullname'] =  $row['first_name'].' '.$row['last_name']; } else { $row['user_fullname'] = $row['username']; }
		$rows[] = $row;
	}
	echo json_encode($rows);
}				
?>
<div class="row col-sm-12">

	<?php if($sub_view == ""){ ?>
    <div class="panel panel-default">
		<div class="panel-heading"><strong><?php echo $wo['lang']['plugin_point_view_list_shop']; ?></strong></div>
		<div class="panel-body">
							   <small><?php echo $wo['lang']['plugin_point_view_list_shop_desc']; ?>.</small>
			 
			<div class="row panel-body with-table">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover js_dataTable">
						<thead>
							<tr>
								<th><?php echo $wo['lang']['plugin_point_id']; ?></th>
								<th><?php echo $wo['lang']['plugin_point_user']; ?></th>
								<th>email</th>							
								<th>Points</th>
								<th><?php echo $wo['lang']['plugin_point_options']; ?></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($rows as $row){ ?>
							<tr>
								<td><?php echo $row['user_id']; ?></td>
								<td><a target="_blank" class="x-image sm" href="<?php echo $wo['config']['site_url']; ?>/<?php echo $row['username']; ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $row['user_fullname']; ?>" style="background-image:url(<?php echo $wo['config']['site_url']; ?>/<?php echo $row['avatar']; ?>);">
									</a></td>
								<td><?php echo $row['email']; ?></td>
								<td><?php echo $row['totalearned']; ?></td>
								<td>								
									<a href="<?php echo $wo['config']['site_url']; ?>/index.php?link1=admin-plugins&view=points_users&sub_view=<?php echo $row['user_id']; ?>" class="btn btn-xs btn-primary">
										<i class="fa fa-pencil"></i>
									</a>
								</td>
							</tr>
							<?php }//F ?>
						</tbody>
					</table>
				</div>
			</div>
				
		</div>
	</div>
	<?php }else{ ?>

	<?php /* box 3 */ ?>
	<div class="panel panel-default" id="points_vault">
		<div class="panel-heading light clearfix mt5">
			<div class="col-sm-7">
				<strong>Point users view</strong>
			</div>
		</div>
		<div class="panel-body">
			<small><?php echo $wo['lang']['plugin_point_text_include_total_points']; ?>.</small>
			<div class="mt20">
				<div class="col-sm-5">
					<strong><?php echo $wo['lang']['plugin_point_balance_m']; ?>:</strong> <?php echo $user_points; ?> <?php echo $wo['lang']['plugin_point_points']; ?>
				</div>
				<div class="col-sm-7">
					<strong><?php echo $wo['lang']['plugin_point_total_points_earned_m']; ?>:</strong> <?php echo $user_points_totalearned; ?> <?php echo $wo['lang']['plugin_point_points']; ?>
				</div>
				<div class="col-sm-12">
					<?php if($user_points_totalearned != 0){ ?><strong><?php echo $wo['lang']['plugin_point_star_rating_m']; ?>:</strong> <?php echo $user_rank; ?> <?php echo $wo['lang']['plugin_point_place']; ?><?php } else { ?><?php echo $wo['lang']['plugin_point_not_ranked']; ?><?php } ?>
				</div>
			</div>
		</div>
	</div>
			 
	<div class="panel panel-default points_content">
		<div class="panel-heading light clearfix mt5">
			<div class="col-sm-7">
				<strong><?php echo $wo['lang']['plugin_point_my_transaction_history']; ?></strong> <br />
			</div>	
			<div class="pull-right">You have <strong class="total_invites"><?php echo $user_points; ?></strong> <?php echo $wo['lang']['plugin_point_points']; ?></div>
		</div>
		<div class="panel-body">
			<small><?php echo $wo['lang']['plugin_point_text_include_post']; ?>.</small>
		
			<div class="row mt20">			
				<?php if($total_items == 0){ ?>
					<div style="text-align:center;"><?php echo $wo['lang']['plugin_point_no_have_points']; ?>.</div>
				<?php } else { ?> 
					<div class="panel-body table-responsive">
						<table class="table table-striped">
							<thead>
								<tr>
									<th><?php echo $wo['lang']['plugin_point_description']; ?></th>
									<th><?php echo $wo['lang']['plugin_point_amount']; ?></th>
									<th><?php echo $wo['lang']['plugin_point_status']; ?></th>
									<th><?php echo $wo['lang']['plugin_point_date']; ?></th>                
								</tr>
							</thead>

							<tbody class="ads_list_content">
								<?php foreach($items as $item){ ?>
									<tr>			
									<td id="invite_<?php echo $item['id']; ?>" title="<?php echo $item['text']; ?>"><?php echo truncate($item['text'], 16 ,true); ?></td>
									<td><?php echo $item['amount']; ?></td>	
									<td><?php echo $item['state']; ?></td>
									<td class="post-time"><a class="js_moment" data-time="<?php echo $item['date']; ?>"><?php echo $item['_date']; ?></a></td>	
									</tr>
								<?php }//F ?>
							</tbody>
						</table>
					</div>	
				<?php } ?>
			</div>					
		</div>
		
	</div>
	<?php /* box 3 */ ?>
		   
<?php } ?>
</div>