<div class="page-margin">
   <div class="row">
      <?php if ($wo['loggedin'] == true) { ?><div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div><?php } ?>
      <div class="col-md-<?php echo ($wo['loggedin'] == true) ? '7': '9';?> <?php echo ($wo['loggedin'] == true) ? 'middlecol': 'singlecol-guest';?>">
	  <center><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- mumblit456 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-4231261115880991"
     data-ad-slot="3638237504"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></center>
         <?php echo Wo_LoadPage('story/content'); ?>
      </div>
	  <div class="sidebar">
	  <h3>Post Statistics</h3><hr>
	  <span class="stat-item"><i class="fa fa-podcast fa-lg" title="Mumbl Views" style="color: purple;"></i> <?php echo $wo['story']['views'];?> Total Mumbl Views</span><br><br><span class="stat-item"><i class="fa fa-share-alt-square fa-lg" title="Shares" style="color: blue;"></i> <?php echo $wo['story']['shares'];?> Total Shares</span><br><br><span class="stat-item"><i class="far fa-paper-plane fa-lg" style="color: red;" title="Link Clicks"></i> <?php echo $wo['story']['lclicks'];?> Total Preview Clicks
            </span> <br><br><center><span class="like-emo post-reactions-icons-<?php echo $wo['story']['id']; ?>">
				<?php echo Wo_GetPostReactions($wo['story']['id']);?></center>
              </span>
   </div>
</div>
<?php
if (!empty($_GET['ref'])) {
?>
<script type="text/javascript">
$.fn.scrollTo = function( target, options, callback ){
  if(typeof options == 'function' && arguments.length == 2){ callback = options; options = target; }
  var settings = $.extend({
    scrollTarget  : target,
    offsetTop     : 75,
    duration      : 500,
    easing        : 'swing'
  }, options);
  return this.each(function(){
    var scrollPane = $(this);
    var scrollTarget = (typeof settings.scrollTarget == "number") ? settings.scrollTarget : $(settings.scrollTarget);
    var scrollY = (typeof scrollTarget == "number") ? scrollTarget : scrollTarget.offset().top + scrollPane.scrollTop() - parseInt(settings.offsetTop);
    scrollPane.animate({scrollTop : scrollY }, parseInt(settings.duration), settings.easing, function(){
      if (typeof callback == 'function') { callback.call(this); }
    });
  });
}

$(function () {
  
  var comment_reply = $("#comment_<?php echo $_GET['ref']?>");
  Wo_ViewMoreReplies(<?php echo $_GET['ref']?>);
  setTimeout(function(){
     if (comment_reply.length) {
        $('body').scrollTo("#comment_<?php echo $_GET['ref']?>");
        $("#comment_<?php echo $_GET['ref']?>").addClass("light").delay(1000).queue(function(next){
           $(this).removeClass("light");
           next();
        });
     }
  }, 500);
  
});
</script>
<?php } ?>
