<tr class="setting-postlist" id="<?php echo $wo['langs_'];?>">
   <td><?php echo $wo['langs'];?></td>
   <td>
      <a class="delete-post pointer" href="<?php echo $wo['config']['site_url']?>/index.php?link1=admin-plugins&view=edit_lang&id=<?php echo $wo['langs_'];?>"><i class="fa fa-pencil-square progress-icon" data-icon="trash-o"></i> Edit language</a> <?php /*| 
      <span class="delete-field pointer" onclick="delete_lang('<?php echo $wo['langs_'];?>');"><i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> Delete language</span>*/ ?>
   </td>
</tr>