<?php /* beers */
  //get beers
     $beers = beer::get_beers($wo['user']['user_id']);
  
  // get profile friends
     $friends_count = count(Wo_GetFollowing($wo['user']['user_id'],'sidebar',10));
   
  // get profile friends_suggest
    $friends = array();
	if($friends_count > 0) { $friends = beer::get_friends($wo['user']['user_id']); }
	
 ?>
<div class="content_beers">       
        <?php /* center panel 1 */ ?>
                <div class="panel panel-default">
                    <div class="panel-heading light clearfix mt5">
                        <div class="col-sm-6">
                            <strong><?php echo $wo['lang']['plugin_beer_beers']; ?></strong>
						</div>	
						<div class="col-sm-6">
<input type="text" name="beer" class="text_search_beer" placeholder="<?php echo $wo['lang']['plugin_beer_beer_search_friend']; ?>"/>
	<div class="dropdown-menu_page page_auto-complete" id="list_f_beers"><ul id="typeahead_list_f_beer"></ul></div>
	                     </div>
                        
                    </div>
                    <div class="panel-body row">
                        <?php if(count($beers) > 0){ ?>
                            <ul>
                                <?php 
									foreach($beers as $beer){
										$suggest = 0;
										include "ajax_beer.phtml";
									}
								?>
                            </ul>
                        <?php } else { ?>
                            <p class="text-center text-muted">
                                <?php echo $wo['lang']['plugin_beer_beer_no_available']; ?>
                            </p>
                        <?php } ?>

                    </div>
                </div>
        <?php /* center panel 1 */ ?>
		
		<?php /* center panel 2 */ ?>
                <div class="panel panel-default">
                    <div class="panel-heading light clearfix">
                        <div class="mt5">
                            <strong><?php echo $wo['lang']['plugin_beer_beer_suggest']; ?></strong>
                        </div>
                    </div>
                    <div class="panel-body row">
                        <?php if(count($friends) > 0){ ?>
                            <ul>
                                <?php 
									foreach($friends as $beer){
										$suggest = 1;
										include "ajax_beer.phtml";
									}
								?>
                            </ul>
                        <?php } else { ?>
                            <p class="text-center text-muted">
                                <?php echo $wo['lang']['plugin_beer_beer_suggest_no_available']; ?>
                            </p>
                        <?php } ?>

                    </div>
                </div>
            
        <?php /* center panel 2 */ ?>
</div>