<?php
	global $ad, $ad_id, $ad_content;
/* page content */
?>

<div class="container mt20">
	<div class="row">
		<div class="col-md-11">
		
			<?php /* header bar */ ?>
				<div class="col-sm-12" style="padding:0px;">
					<?php include "ads_header.phtml"; ?>
				</div>
			<?php /* header bar */ ?>	
		
			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $ad_content['title']; ?></div>
				<div class="panel-body">
				<?php 
				if(!empty($ad_content['template'] != 'ads/')){ 	
					include $ad_content['template'];
				}
				?>
				</div>
			</div>
		</div>

		<?php /* left panel */ ?>
	</div>
</div>

<?php
/* page content */
?>