<?php if($wo['system']['ads_enable_stripe'] == 1){ ?>
<li>
	<form action="<?php echo $wo['config']['site_url']; ?>/index.php?link1=ads-activate&ad_id=<?php echo $ad['id']; ?>&action=stripe&type=thank_you" method="POST">
		<script
			src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			data-key="<?php if($wo['system']['stripe_publishable_key'] != ''){ 
				echo $wo['system']['stripe_publishable_key'];
			} else { 
				echo 'pk_test_FW6bir1XIC0ZeTFxHJ4SfPTV';
			} ?>"
			data-amount="<?php echo (int)($ad['price'] * 100); ?>"
			data-bitcoin="true"
			data-name="Active Ads"
			data-description="<?php echo $ad['campaign_name']; ?>"
			data-image="<?php echo $wo['config']['site_url']; ?>/assets/plugins/ads/images/stripe-icon.png"
			data-locale="auto">
		</script>
	</form>
</li>	
<?php } ?>	