<span id="like-button" class="btn btn-default stat-item" title="<?php echo $wo['lang']['like'];?>">
  <div class="story-react-container">
     <?php if($wo['story']['is_liked'] === true){ 
	    echo getReactButtonTemplate('', $wo['user']['user_id'], $wo['story']['id']);
     } else { ?>
		 <span class="text-link story-like-btn opt" onclick="set_reaction($(this), 'like', <?php echo $wo['story']['id']; ?>);" title="<?php echo $wo['lang']['like']; ?>">
		 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <?php echo $wo['lang']['like']; ?></span>
     <?php } ?>
     <span class="emotionreaction"></span>
  </div>
</span>